### ISSUE TITLE
I try to use a new version of the plug-in. But I can't compile the plug-in

### ISSUE THREAD

**Issue by salier** [wongfei/ue4-mediapipe-plugin#10]
![image](https://user-images.githubusercontent.com/28691601/132365482-8db485dd-731f-4aae-af97-8976875e39ea.png)
Multiple attempts failed to compile successfully

**Comment by salier** [comment]
Older versions of plug-ins cannot be packaged.
![image](https://user-images.githubusercontent.com/28691601/132366302-f9f105ec-cb97-4070-8407-fcc4d50486cc.png)
[UBT-MediaPipeDemo-Win64-Development.txt](https://github.com/wongfei/ue4-mediapipe-plugin/files/7122442/UBT-MediaPipeDemo-Win64-Development.txt)

**Comment by wongfei** [comment]
please use Visual Studio 2019 instead of 2017, protobuf library is compiled with 2019 and will not link with older versions

**Comment by salier** [comment]
![image](https://user-images.githubusercontent.com/28691601/132637769-463fd546-2f45-4903-a9e1-564516851017.png)
I use the 2019 version of vs. it hasn't been modified, but it still can't be packaged normally

**Comment by salier** [comment]
I tried again. Neither the old version plug-in nor the new version plug-in can compile the plug-in.
![image](https://user-images.githubusercontent.com/28691601/132639975-6b322c24-8007-4ac8-9e5e-dbe739bd76fd.png)
Use vs2019
The old plug-in before was compiled by this computer. Now it can't compile normally. It can't package the program

**Comment by salier** [comment]
Running D:/UE_4.26/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="E:/unral project/apipe/MediaPipeDemo.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
WARNING: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
E:\unral project\apipe\Plugins\VRM4U\VRM4U.uplugin: warning: The 'Developer' module type has been deprecated in 4.24.
Creating makefile for UE4Editor (no existing makefile)
@progress push 5%
Parsing headers for UE4Editor
  Running UnrealHeaderTool "E:\unral project\apipe\MediaPipeDemo.uproject" "E:\unral project\apipe\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\Administrator\AppData\Local\UnrealBuildTool\Log_UHT.txt" -installed
Reflection code generated for UE4Editor in 6.269751 seconds
@progress pop
Building UE4Editor...
Using Visual Studio 2019 14.29.30133 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133) and Windows 10.0.20348.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Building 52 actions with 8 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 2%
  [1/52] Default.rc2
  @progress 'Compiling C++ source code...' 4%
  [2/52] Default.rc2
  @progress 'Compiling C++ source code...' 6%
  [3/52] Default.rc2
  @progress 'Compiling C++ source code...' 8%
  [4/52] Default.rc2
  @progress 'Compiling C++ source code...' 10%
  [5/52] Default.rc2
  @progress 'Compiling C++ source code...' 12%
  [6/52] Default.rc2
  @progress 'Compiling C++ source code...' 13%
  [7/52] ump_shared.dll
  @progress 'Compiling C++ source code...' 15%
  [8/52] opencv_world3410.dll
  @progress 'Compiling C++ source code...' 17%
  [9/52] SharedPCH.UnrealEd.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 19%
  [10/52] Module.VRM4UEditor.gen.cpp
  @progress 'Compiling C++ source code...' 21%
  [11/52] VRM4UMisc.cpp
  @progress 'Compiling C++ source code...' 23%
  [12/52] UE4Editor-VRM4UMisc.lib
    ???ڴ????? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UMisc\UE4Editor-VRM4UMisc.lib ?Ͷ??? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UMisc\UE4Editor-VRM4UMisc.exp
  @progress 'Compiling C++ source code...' 25%
  [13/52] Module.VRM4UEditor.cpp
  @progress 'Compiling C++ source code...' 27%
  [14/52] Module.VRM4UImporter.gen.cpp
  @progress 'Compiling C++ source code...' 29%
  [15/52] UE4Editor-VRM4UEditor.lib
    ???ڴ????? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UEditor\UE4Editor-VRM4UEditor.lib ?Ͷ??? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UEditor\UE4Editor-VRM4UEditor.exp
  @progress 'Compiling C++ source code...' 31%
  [16/52] Module.VRM4U.gen.cpp
  @progress 'Compiling C++ source code...' 33%
  [17/52] Module.VRM4UImporter.cpp
  @progress 'Compiling C++ source code...' 35%
  [18/52] UE4Editor-VRM4UImporter.lib
    ???ڴ????? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UImporter\UE4Editor-VRM4UImporter.lib ?Ͷ??? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UImporter\UE4Editor-VRM4UImporter.exp
  @progress 'Compiling C++ source code...' 37%
  [19/52] SharedPCH.Engine.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 38%
  [20/52] SharedPCH.Engine.RTTI.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 40%
  [21/52] Module.VRM4U.cpp
  @progress 'Compiling C++ source code...' 42%
  [22/52] Module.VRM4ULoader.gen.cpp
  @progress 'Compiling C++ source code...' 44%
  [23/52] Module.MediaPipe.gen.cpp
  @progress 'Compiling C++ source code...' 46%
  [24/52] anchor.pb.cc
  @progress 'Compiling C++ source code...' 48%
  [25/52] mesh_3d.pb.cc
  @progress 'Compiling C++ source code...' 50%
  [26/52] environment.pb.cc
  @progress 'Compiling C++ source code...' 52%
  [27/52] rect.pb.cc
  @progress 'Compiling C++ source code...' 54%
  [28/52] locus.pb.cc
  @progress 'Compiling C++ source code...' 56%
  [29/52] classification.pb.cc
  @progress 'Compiling C++ source code...' 58%
  [30/52] location_data.pb.cc
  @progress 'Compiling C++ source code...' 60%
  [31/52] image_format.pb.cc
  @progress 'Compiling C++ source code...' 62%
  [32/52] image_file_properties.pb.cc
  @progress 'Compiling C++ source code...' 63%
  [33/52] matrix_data.pb.cc
  @progress 'Compiling C++ source code...' 65%
  [34/52] landmark.pb.cc
  @progress 'Compiling C++ source code...' 67%
  [35/52] optical_flow_field_data.pb.cc
  @progress 'Compiling C++ source code...' 69%
  [36/52] detection.pb.cc
  @progress 'Compiling C++ source code...' 71%
  [37/52] rasterization.pb.cc
  @progress 'Compiling C++ source code...' 73%
  [38/52] UE4Editor-VRM4U.lib
    ???ڴ????? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4U\UE4Editor-VRM4U.lib ?Ͷ??? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4U\UE4Editor-VRM4U.exp
  @progress 'Compiling C++ source code...' 75%
  [39/52] UE4Editor-VRM4UEditor.dll
    ???ڴ????? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UEditor\UE4Editor-VRM4UEditor.suppressed.lib ?Ͷ??? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4UEditor\UE4Editor-VRM4UEditor.suppressed.exp
  @progress 'Compiling C++ source code...' 77%
  [40/52] UE4Editor-VRM4U.dll
    ???ڴ????? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4U\UE4Editor-VRM4U.suppressed.lib ?Ͷ??? E:\unral project\apipe\Plugins\VRM4U\Intermediate\Build\Win64\UE4Editor\Development\VRM4U\UE4Editor-VRM4U.suppressed.exp
  @progress 'Compiling C++ source code...' 79%
  [41/52] face_geometry.pb.cc
  @progress 'Compiling C++ source code...' 81%
  [42/52] geometry_pipeline_metadata.pb.cc
  @progress 'Compiling C++ source code...' 83%
  [43/52] time_series_header.pb.cc
  @progress 'Compiling C++ source code...' 85%
  [44/52] Module.MediaPipe.cpp
  @progress 'Compiling C++ source code...' 87%
  [45/52] UE4Editor-MediaPipe.lib
    ???ڴ????? E:\unral project\apipe\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.lib ?Ͷ??? E:\unral project\apipe\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.exp
  @progress 'Compiling C++ source code...' 88%
  [46/52] UE4Editor-MediaPipe.dll
    ???ڴ????? E:\unral project\apipe\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.suppressed.lib ?Ͷ??? E:\unral project\apipe\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.suppressed.exp

I updated the version of vs2019. But I still can't compile the new plug-in (100% and then the compilation fails)
The above is a part of the log
![image](https://user-images.githubusercontent.com/28691601/132646350-24b82b8e-b71e-4b10-9152-31e45ec6c691.png)

**Comment by wongfei** [comment]
1. download latest plugin version to clean folder
2. right click MediaPipeDemo.uproject and select "Generate Visual Studio project files"
3. right click MediaPipeDemo.sln and select open with Visual Studio 2019
4. select Development Editor configuration (see screenshot)
5. right click MediaPipeDemo and select rebuild (see screenshot)
6. click View -> Output
7. copy all text from Output window and upload here

![1](https://user-images.githubusercontent.com/13559668/132752615-258f71d8-9944-4a55-98cf-2e95e0962d27.jpg)

![2](https://user-images.githubusercontent.com/13559668/132752624-6069b0d7-c64a-436e-94dd-740ec4eb0c60.jpg)

**Comment by salier** [comment]
![image](https://user-images.githubusercontent.com/28691601/132783758-e833ebf8-c1e3-4923-8a89-c7b5aac4dc21.png)

**Comment by salier** [comment]
I am on another computer. I use vs2017 to compile. The plug-in of the old version cannot be packaged. The project cannot be packaged. The new version cannot be opened and compilation fails

**Comment by salier** [comment]
LogSlate: Took 0.000375 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/NotoNaskhArabicUI-Regular.ttf' (144K)
UATHelper: 打包插件任务 (窗口): Running AutomationTool...
UATHelper: 打包插件任务 (窗口): Parsing command line: BuildPlugin -Plugin="D:/unreal project/apipe/Plugins/MediaPipe/MediaPipe.uplugin" -Package="D:/unreal project/apipe/MediaPipe" -CreateSubFolder
UATHelper: 打包插件任务 (窗口): Copying 475 file(s) using max 64 thread(s)
UATHelper: 打包插件任务 (窗口): Reading plugin from D:\unreal project\apipe\MediaPipe\HostProject\Plugins\MediaPipe\MediaPipe.uplugin...
UATHelper: 打包插件任务 (窗口): Building plugin for host platforms: Win64
UATHelper: 打包插件任务 (窗口): Running: D:\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Editor Win64 Development -Project="D:\unreal project\apipe\MediaPipe\HostProject\HostProject.uproject" -plugin="D:\unreal project\apipe\MediaPipe\HostProject\Plugins\MediaPipe\MediaPipe.uplugin" -iwyu -noubtmakefiles -manifest="D:\unreal project\apipe\MediaPipe\HostProj
ect\Saved\Manifest-UE4Editor-Win64-Development.xml" -nohotreload -log="C:\Users\ҹ??ѩ\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE_4.26\UBT-UE4Editor-Win64-Development.txt"
UATHelper: 打包插件任务 (窗口):   Parsing headers for UE4Editor
UATHelper: 打包插件任务 (窗口):     Running UnrealHeaderTool "D:\unreal project\apipe\MediaPipe\HostProject\HostProject.uproject" "D:\unreal project\apipe\MediaPipe\HostProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\ҹ??ѩ\AppDa
ta\Roaming\Unreal Engine\AutomationTool\Logs\D+UE_4.26\UHT-UE4Editor-Win64-Development.txt" -installed
UATHelper: 打包插件任务 (窗口):   Reflection code generated for UE4Editor in 4.1480417 seconds
UATHelper: 打包插件任务 (窗口):   Writing manifest to D:\unreal project\apipe\MediaPipe\HostProject\Saved\Manifest-UE4Editor-Win64-Development.xml
UATHelper: 打包插件任务 (窗口):   Building UE4Editor...
UATHelper: 打包插件任务 (窗口):   Using Visual Studio 2017 14.16.27045 toolchain (D:\visual studio\VC\Tools\MSVC\14.16.27023) and Windows 10.0.17763.0 SDK (D:\Windows Kits\10).
UATHelper: 打包插件任务 (窗口):   Building 24 actions with 16 processes...
UATHelper: 打包插件任务 (窗口):     [1/24] Default.rc2
UATHelper: 打包插件任务 (窗口):     [2/24] SharedPCH.Engine.RTTI.ShadowErrors.cpp
UATHelper: 打包插件任务 (窗口):     [3/24] Module.MediaPipe.gen.cpp
UATHelper: 打包插件任务 (窗口):     [4/24] image_format.pb.cc
UATHelper: 打包插件任务 (窗口):     [5/24] rect.pb.cc
UATHelper: 打包插件任务 (窗口):     [6/24] face_geometry.pb.cc
UATHelper: 打包插件任务 (窗口):     [7/24] environment.pb.cc
UATHelper: 打包插件任务 (窗口):     [8/24] optical_flow_field_data.pb.cc
UATHelper: 打包插件任务 (窗口):     [9/24] mesh_3d.pb.cc
UATHelper: 打包插件任务 (窗口):     [10/24] time_series_header.pb.cc
UATHelper: 打包插件任务 (窗口):     [11/24] anchor.pb.cc
UATHelper: 打包插件任务 (窗口):     [12/24] rasterization.pb.cc
UATHelper: 打包插件任务 (窗口):     [13/24] image_file_properties.pb.cc
UATHelper: 打包插件任务 (窗口):     [14/24] geometry_pipeline_metadata.pb.cc
UATHelper: 打包插件任务 (窗口):     [15/24] landmark.pb.cc
UATHelper: 打包插件任务 (窗口):     [16/24] location_data.pb.cc
UATHelper: 打包插件任务 (窗口):     [17/24] detection.pb.cc
UATHelper: 打包插件任务 (窗口):     [18/24] matrix_data.pb.cc
UATHelper: 打包插件任务 (窗口):     [19/24] Module.MediaPipe.cpp
UATHelper: 打包插件任务 (窗口):     [20/24] classification.pb.cc
UATHelper: 打包插件任务 (窗口):     [21/24] locus.pb.cc
UATHelper: 打包插件任务 (窗口):     [22/24] UE4Editor-MediaPipe.lib
UATHelper: 打包插件任务 (窗口):       ???ڴ????? D:\unreal project\apipe\MediaPipe\HostProject\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.lib ?Ͷ??? D:\unreal project\apipe\MediaPipe\HostProject\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.exp
UATHelper: 打包插件任务 (窗口):     [23/24] UE4Editor-MediaPipe.dll
UATHelper: 打包插件任务 (窗口):       ???ڴ????? D:\unreal project\apipe\MediaPipe\HostProject\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.suppressed.lib ?Ͷ??? D:\unreal project\apipe\MediaPipe\HostProject\Plugins\MediaPipe\Intermediate\Build\Win64\UE4Editor\Development\MediaPipe\UE4Editor-MediaPipe.suppressed.exp
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(substitute.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(any_lite.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(any.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(descriptor.pb.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(tokenizer.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(descriptor_database.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(dynamic_message.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(map_field.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(stringprintf.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(io_win32.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(text_format.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(strutil.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(zero_copy_stream_impl_lite.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(descriptor.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(extension_set_heavy.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(implicit_weak_message.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(status.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(int128.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(message.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(reflection_ops.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(wire_format.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(extension_set.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(message_lite.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(generated_message_util.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(unknown_field_set.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(generated_message_reflection.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(repeated_field.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(common.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(coded_stream.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(arena.obj) : error LNK2001: ?޷????????ⲿ???? __CxxFrameHandler4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(dynamic_message.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(substitute.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(any_lite.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(any.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(io_win32.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(text_format.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(tokenizer.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(descriptor_database.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(descriptor.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(map_field.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(stringprintf.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(int128.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(strutil.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(zero_copy_stream.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(zero_copy_stream_impl_lite.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(wire_format_lite.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(extension_set.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(extension_set_heavy.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(status.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(generated_message_reflection.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(message.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(reflection_ops.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(wire_format.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(message_lite.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(generated_message_util.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(parse_context.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(unknown_field_set.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(repeated_field.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(common.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(coded_stream.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(arena.obj) : error LNK2001: ?޷????????ⲿ???? __GSHandlerCheck_EH4
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(arena.obj) : error LNK2019: ?޷????????ⲿ???? __dyn_tls_on_demand_init???÷????ں??? "public: void __cdecl google::protobuf::internal::ArenaImpl::AddCleanup(void *,void (__cdecl*)(void *))" (?AddCleanup@ArenaImpl@internal@protobuf@google@@QEAAXPEAXP6AX0@Z@Z) ?б????Ş    libprotobuf.lib(arena.obj) : error LNK2019: ?޷????
????ⲿ???? __tls_guard???÷????ں??? "public: void __cdecl google::protobuf::internal::ArenaImpl::AddCleanup(void *,void (__cdecl*)(void *))" (?AddCleanup@ArenaImpl@internal@protobuf@google@@QEAAXPEAXP6AX0@Z@Z) ?б???
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(text_format.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(dynamic_message.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(any.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(extension_set_heavy.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(implicit_weak_message.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(descriptor.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(map_field.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(generated_message_reflection.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(message.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(reflection_ops.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(wire_format.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_begin_initialize
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(text_format.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(dynamic_message.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(any.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(extension_set_heavy.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(implicit_weak_message.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(descriptor.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(map_field.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(generated_message_reflection.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(message.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(reflection_ops.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     libprotobuf.lib(wire_format.obj) : error LNK2001: ?޷????????ⲿ???? __imp___std_init_once_complete
UATHelper: 打包插件任务 (窗口):     D:\unreal project\apipe\MediaPipe\HostProject\Plugins\MediaPipe\Binaries\Win64\UE4Editor-MediaPipe.dll : fatal error LNK1120: 6 ???޷????????ⲿ???Took 37.5466702s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: 打包插件任务 (窗口): UnrealBuildTool failed. See log for more details. (C:\Users\ҹ??ѩ\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE_4.26\UBT-UE4Editor-Win64-Development.txt)
UATHelper: 打包插件任务 (窗口): AutomationTool exiting with ExitCode=6 (6)
UATHelper: 打包插件任务 (窗口): BUILD FAILED
This is the log of trying to package the plug-in using 2017vs
