### ISSUE TITLE
when i disable overlay, hand landmark doesn't work

### ISSUE THREAD

**Issue by maongart** [wongfei/ue4-mediapipe-plugin#11]
i am using holistic with iris that can use all of stuffs of plugin.  when i disable overlay, hand landmark doesn't work. pose_world_landmark is fine but hand is not working. 

and is there anyway to convert output video to ue media texture?

**Comment by wongfei** [comment]
run the scene with disabled overlay, then upload graph config file you using (*.pbtxt) and "ue4-mediapipe-plugin\Saved\Logs\MediaPipeDemo.log"

output to texture is not implemented right now
