### ISSUE TITLE
Can I get  the WebCamera Frame or data

### ISSUE THREAD

**Issue by RailGun00** [wongfei/ue4-mediapipe-plugin#12]
In my project I need get the same webcamera so Can i Get the WebCamera Frame or data?

**Comment by wongfei** [comment]
access to input/output frames will be available in future versions

**Comment by IvanSobko** [comment]
Hello. Sorry to bother you, but is there any progress with input/output frames feature? Thanks for plugin btw, it helped me a lot

**Comment by wongfei** [comment]
> Hello. Sorry to bother you, but is there any progress with input/output frames feature? Thanks for plugin btw, it helped me a lot

As for now that feature is dropped. Nice integration with UE4 will take a time and the profit is doubtful.. 

Maybe for your specific use case the wrapper library can be modified with minimal effort (for ex. store the frame to memory buffer or shared memory), see: https://github.com/wongfei/mediapipe/blob/unreal/mediapipe/unreal/ump_pipeline.cc#L302

**Comment by wongfei** [comment]
https://github.com/wongfei/ue4-mediapipe-plugin/commit/3d3710283b56a646c8524c50234e9e8b83947e6b
