### ISSUE TITLE
macos

### ISSUE THREAD

**Issue by UmkaApps** [wongfei/ue4-mediapipe-plugin#15]
Good afternoon. I know that the system requirements are Windows, but I still tried to compile the project under Mac OS Mojave. The problem is that the compilation is successful, but when the project is launched there is no Pipeline component and all the components of your plugin. In the plugins editor, it is listed, but there are no functions in Blueprints. Is it possible to compile the plugin under MacOS?

**Comment by wongfei** [comment]
Only Win64 is supported, check file "Plugins\MediaPipe\MediaPipe.uplugin".

You may try modifying it to:
"WhitelistPlatforms": [ "Win64", "Mac" ]

But then you have to compile mediapipe wrapper and libprotobuf and solve other who know what problems..
