### ISSUE TITLE
What about the Selfie-Segmentation solution ?

### ISSUE THREAD

**Issue by jimver04** [wongfei/ue4-mediapipe-plugin#18]
Is there in your plans to implement it ? Can you provide hints for our selves to program it ?

**Comment by wongfei** [comment]
Self-segmentation would require fetching segmented frames from mediapipe and uploading them to ue4 texture. Not planned in near future. But if I remember correctly MediaPipeUnityPlugin can do it.

In case you want to solve it,

attach to pipeline:
https://github.com/wongfei/mediapipe/blob/unreal/mediapipe/unreal/ump_pipeline.cc#L180

callback to ue4 via interface:
https://github.com/wongfei/mediapipe/blob/unreal/mediapipe/unreal/ump_api.h#L84

inside ue4 create dynamic texture and update it:
https://github.com/wongfei/ue4-gstreamer/blob/master/Plugins/GStreamer/Source/GStreamer/Private/GstTexture.cpp#L105

some work required, huh :)

**Comment by colinbouvry** [comment]
Hello,
I vote for this feature !
Not sure i have enough skill.
