### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by oneemptyearthling** [wongfei/ue4-mediapipe-plugin#19]
I cannot see where the webcam is accessed.
How would I implement this example to run on Android using the Phone's camera.

**Comment by wongfei** [comment]
Android is not implemented.

**Comment by oneemptyearthling** [comment]
thanks for the response. How would I change the camera input? as the inputfile and camId appear blank when i read them.

**Comment by wongfei** [comment]
MediaPipePipelineComponent has properties:

InputFile (string) -> will play from file
CameraId (int) -> will capture camera with specific ID (0 means default)

should be assigned before calling MediaPipePipelineComponent::Start()

**Comment by oneemptyearthling** [comment]
thanks for the clarification.
