### ISSUE TITLE
Compiled the UE4 project. How to connect the camera?

### ISSUE THREAD

**Issue by PinkMediaGroup** [wongfei/ue4-mediapipe-plugin#2]
I have compiled the project and when I started to run the level the MediaPipe window appears black.  I guess that is not connected to the webcam. Can you explain me where or in which config file can I address the webcam?

Best regards,
[](url)
![Screenshot 2021-07-28 232117](https://user-images.githubusercontent.com/49684107/127397789-c184f81d-e6a4-43ee-8860-e5a885a9fd81.jpg)

Mirko

**Comment by wongfei** [comment]
1. Check Output Log for errors

2. Edit Content/MediaPipe/Blueprints/MP_Pipeline and change CameraId to 1 or 2.

![mp3](https://user-images.githubusercontent.com/13559668/127399182-1eca7602-0e75-42f7-9493-ba6b20cc3835.jpg)

3. In case it doesn't work upload ue4-mediapipe-plugin\Saved\Logs\MediaPipeDemo.log

**Comment by PinkMediaGroup** [comment]
Thank you. It works

**Comment by PinkMediaGroup** [comment]
I tried to change the camera resolution, but the mediapipe window appear to be same. Are there any settings in the code where I can change the input resolution., frame rate?
