### ISSUE TITLE
Handedness 

### ISSUE THREAD

**Issue by HumaintRamsey** [wongfei/ue4-mediapipe-plugin#20]
Hello, I'm having a lot of fun with this plugin, however
It would be useful to be able to know which hand, left or right, each detection is. 
The problem I'm having at the moment is that it starts out detecting both my hands, one of them is detection 1 and the other is detection 2, but if it looses detection of hand 1, then detection 2 becomes detection 1 since there is only one detection, which means anything that was using the landmarks of the previous detection 1 is teleported to the landmarks of the new detection 1. If I knew the handedness of each detection then I could tell anything using the landmarks to pay attention to handedness rather than detection order of the hands.

**Comment by wongfei** [comment]
check latest commit, MediaPipeClassificationObserverComponent, Maps/HandLandmarks.umap

![handedness](https://user-images.githubusercontent.com/13559668/143057118-9e500a25-000d-4d4a-b4d8-b8e0cbe56d60.jpg)
