### ISSUE TITLE
holistic landmarks detection does not output hand detection confidence

### ISSUE THREAD

**Issue by increase24** [wongfei/ue4-mediapipe-plugin#24]
Hi! Wongfei,
When running with this plugin, I encountered the following problem:
The hand landmarks detection (configured by multi_hand_landmarks.pbtxt) output hand detection confidence, while the holistic landmarks detection (configured by holistic_landmarks.pbtxt or holistic_with_iris.pbtxt) does not output the hand detection confidence.
How to solve this issue? Can I just modify holistic_landmarks.pbtxt to add the corresponding output without changing the code structure.
Looking forward to your reply!

**Comment by wongfei** [comment]
see MediaPipeClassificationObserverComponent and how it used in MP_LandmarkObserver DrawDetections

**Comment by increase24** [comment]
> 

thank you for your reply!
I am confused about another question: where is the calculators in pbtxts being defined, such as HolisticLandmarkCpu, PacketPresenceCalculator, FaceLandmarksFromPoseToRecropRoi ......

**Comment by wongfei** [comment]
they are coming with mediapipe sdk, for ex: https://github.com/wongfei/mediapipe/tree/master/mediapipe/graphs/holistic_tracking
