### ISSUE TITLE
UE5 Preview Binaries 

### ISSUE THREAD

**Issue by ang88myt** [wongfei/ue4-mediapipe-plugin#25]
Possible to provide UE5 Preview Binaries for mediapipe plugin? @wongfei

**Comment by fpibbs** [comment]
Cannot compile unfortunately on UE5pre1

**Comment by wongfei** [comment]
https://github.com/wongfei/ue4-mediapipe-plugin/commit/d904e08c2ffdbfc3c42868e68765b6902a17e521
