### ISSUE TITLE
UE4.23.1

### ISSUE THREAD

**Issue by aaronvdbrugge** [wongfei/ue4-mediapipe-plugin#26]
Hi Wongfei,

Can I reach out personally to you, to ask how we could use MediaPipe for UE4.23.1?

Thank you for your time, it is valued.

**Comment by wongfei** [comment]
copy dir
"ue4-mediapipe-plugin\Plugins\MediaPipe" to "yourproject423\Plugins\MediaPipe"

delete
"yourproject423\Plugins\MediaPipe\Binaries"
"yourproject423\Plugins\MediaPipe\Intermediate"

edit
"yourproject423\Plugins\MediaPipe\MediaPipe.uplugin"
change 
"EngineVersion": "4.26.0"
to
"EngineVersion": "4.23.0"

edit
"yourproject423\yourproject423.uproject"
add after modules
```
"Plugins": [
	{
		"Name": "MediaPipe",
		"Enabled": true
	}
]
```

launch the project

**Comment by aaronvdbrugge** [comment]
Thank you so much! I'll let you know if anything comes up.

Sincerely / Met vriendelijke groeten,
Aaron van der Brugge

**Comment by aaronvdbrugge** [comment]
So I'm having trouble opening the project in Unity 2.26. I want to see what the scenes look like because it will help me understand how I am supposed to use this plugin. So I open it in Unity 2.26.2, but it asks to rebuild and then I get this error:

![image](https://user-images.githubusercontent.com/45329627/157605917-845c34f7-7fc7-4382-8db1-3bcc80f821ea.png)

Please help?

**Comment by aaronvdbrugge** [comment]
Ah, so I see the plugin only supports Windows. Is there any way to open the project on a Mac?

Will an HTML5 package work?

**Comment by aaronvdbrugge** [comment]
So I tried it on Windows but we are not able to open the project at all in 4.26. What could be the issue?

**Comment by wongfei** [comment]
upload "ue4-mediapipe-plugin\Saved\Logs\MediaPipeDemo.log"

**Comment by aaronvdbrugge** [comment]
It doesn't make a Saved/Logs folder, I checked. :-/

[image: Screen Shot 2022-03-11 at 4.40.57 PM.png]

This is the state of the folder after trying to open it. Please don't mind
the XCode project, I was trying out some stuff to fix it.

Same issue on Windows. Even with the plugin disabled. Using UE4.26.2

Thanks for your time.

Sincerely / Met vriendelijke groeten,
Aaron van der Brugge
