### ISSUE TITLE
About ump_shared.dll

### ISSUE THREAD

**Issue by sixtolink** [wongfei/ue4-mediapipe-plugin#27]
When I try Load ump_shared.dll,the engine stops at 75%.May I refer to your VisualStudio config?
Engine Version:UE5 Pre.
Thansks!

**Comment by wongfei** [comment]
what VS version are you using? ump_shared precompiled with vs2019 and wouldn't work with vs2022

**Comment by sixtolink** [comment]
VS2022.
I have always used ue427 and vs2022. This problem only occurs on ue5pre.

**Comment by wongfei** [comment]
well its preview so anything can happen.. 
i tested on win10.19041 / vs2019 / ue5p2 and it seems to be ok
in case plugin deadlocking try using debugger to attach the process and pinpoint the callstack

**Comment by sixtolink** [comment]
Sorry, I'm not a professional. From the stack information, load into mfcore.dll, the engine will not continue to start. I can't see anything unusual. My environment is win11_22000.527/vs2022/ue5p2.

**Comment by sixtolink** [comment]
I think I found the problem. I tried to change 2019 + ue5p2, but it still didn't work. The wrong place is getdllhandle(). The program stopped loading some DLLs in C;/Windows/System32. I think the engine is not compatible with win11 at present. Maybe you can turn off the issues first.

**Comment by chenshuhao** [comment]
Hello, I also have a problem. Have you found a solution? @sixtolink

**Comment by wongfei** [comment]
https://github.com/wongfei/ue4-mediapipe-plugin/commit/d904e08c2ffdbfc3c42868e68765b6902a17e521
