### ISSUE TITLE
MacOS and HTML5

### ISSUE THREAD

**Issue by aaronvdbrugge** [wongfei/ue4-mediapipe-plugin#28]
Hi Wongfei,

I am currently looking into the code an dusage of the dlls and protobuf.

I am sure with some work this plugin could be edited to also include the MacOS platform, right?

And would it work to build to an HTML5 package?

Are you available for commission?

Thanks,

Aaron

Edit: I asked my colleague on Windows to open the project but he got the same error of not being able to build. He was on UE4.26.2.

**Comment by wongfei** [comment]
maybe with some tuning plugin will work on MacOS, HTML5 likely will not

UE4+HTML5 is buggy hell and no wonder Epic dropped it in next versions

check UnityMediapipePlugin that already cross platform

**Comment by aaronvdbrugge** [comment]
Can I ask why it is likely not to work in an HTML5 build? Like specifically
why? Because that's our ultimate goal, not an app for MacOS. I was just
talking about getting it to work in the engine on a MacOS.

**Comment by wongfei** [comment]
> Can I ask why it is likely not to work in an HTML5 build? Like specifically why?

Because plugin loads third party dlls and external files, does camera capture with OpenCV, maybe something else..

> Also are you available for short project based hire or commission?

Nope, busy right now and not interested in HTML5

**Comment by aaronvdbrugge** [comment]
Should it be workable if I find replacements for the third party dlls?

I guess dll doesn't work on MacOS anyway so I need to find something to
replace them?

Actually I talked to the MediaPipe guys about an HTML5 build and they sent
me to your plugin so I'm surprised to hear it won't work with HTML5. Maybe
MediaPipe works but not this repository specifically because of how you
built it?

Sincerely / Met vriendelijke groeten,
Aaron van der Brugge

**Comment by wongfei** [comment]
This plugin was developed and tested for windows only, the rest is DIY

**Comment by aaronvdbrugge** [comment]
Cool, thanks! Understand.

I would love to open it on Windows but it doesn't work opening in UE4.26.
Do I need to download and use the wrapper or install Python?

**Comment by aaronvdbrugge** [comment]
@wongfei Happy Monday!

I hope you can offer advice on how to open the project at all. Thank you.
