### ISSUE TITLE
I tried to change the camera resolution, but the mediapipe window appear to be same. Are there any settings in the code where I can change the input resolution, frame rate?

### ISSUE THREAD

**Issue by PinkMediaGroup** [wongfei/ue4-mediapipe-plugin#3]
I tried to change the camera resolution, but the mediapipe window appear to be same. Are there any settings in the code where I can change the input resolution, frame rate?

_Originally posted by @PinkMediaGroup in https://github.com/wongfei/ue4-mediapipe-plugin/issues/2#issuecomment-888657918_

**Comment by wongfei** [comment]
Plugin uses cv::VideoCapture inside (see https://github.com/wongfei/mediapipe/blob/unreal/mediapipe/unreal/ump_pipeline.cc#L188)

When setting ResX/ResY/Fps ensure your camera actually supports that resolution

Also try different CaptureApi values (same as cv::VideoCaptureAPIs https://docs.opencv.org/3.4/dc/d3d/videoio_8hpp.html)

cv::CAP_DSHOW -> 700

cv::CAP_MSMF -> 1400

![mp4](https://user-images.githubusercontent.com/13559668/127407832-686d5c13-18d6-4487-975f-c909af706988.jpg)
