### ISSUE TITLE
MediaPipe Plugin support for UE4.27

### ISSUE THREAD

**Issue by tbKorber** [wongfei/ue4-mediapipe-plugin#30]
Hey wongfei,

Can I expect a plugin support for UE4.27? If so any idea when it might be released?
Thank you!

**Comment by wongfei** [comment]
yep it works, just upgrade the proj to 427

**Comment by tbKorber** [comment]
I see, I assume the plugin will still work even though the pop up informs me the plugin was built for 4.26?

**Comment by wongfei** [comment]
edit 
ue4-mediapipe-plugin\Plugins\MediaPipe\MediaPipe.uplugin

change 
"EngineVersion": "4.27.0"

**Comment by tbKorber** [comment]
Thanks!
