### ISSUE TITLE
Packaging MediaPipe with OVRLipSync Error

### ISSUE THREAD

**Issue by tbKorber** [wongfei/ue4-mediapipe-plugin#31]
Hi Wong Fei,

I've tested packaging with only the mediapipe plugin aswell as only the Oculus VR Lip Sync plugin and both are able to be packaged fine on their own. However trying to package them together produces an error that my colleague and I haven't been able to figure out.

If you have any idea why this is happening know of a fix it would be greatly appreciated.

(It seems that Github will wrap the text to fit so it's still difficult to read even when marked as code, sorry)
The Output Log for the Packaging Process:

`LogUObjectHash: Compacting FUObjectHashTables data took   0.80ms
LogMainFrame: Selected target: MediaPipeDemo
LogLauncherProfile: Unable to use promoted target - D:/Unreal Projects/ue4-mediapipe-plugin/Binaries/Win64/MediaPipeDemo-Win64-Shipping.target does not exist.
UATHelper: Packaging (Windows (64-bit)): Running AutomationTool...
UATHelper: Packaging (Windows (64-bit)): Parsing command line: -ScriptsForProject="D:/Unreal Projects/ue4-mediapipe-plugin/MediaPipeDemo.uproject" BuildCookRun -nocompileeditor -installed -nop4 -project="D:/Unreal Projects/ue4-mediapipe-plugin/MediaPipeDemo.uproject" -cook -stage -archive -archivedirectory="D:/Unreal Projects/MediaPipeBuild" -package -ue4exe
="C:\Program Files\Epic Games\UE_4.27\Engine\Binaries\Win64\UE4Editor-Cmd.exe" -clean -compressed -ddc=InstalledDerivedDataBackendGraph -pak -prereqs -distribution -nodebuginfo -targetplatform=Win64 -build -target=MediaPipeDemo -clientconfig=Shipping -utf8output
UATHelper: Packaging (Windows (64-bit)): Setting up ProjectParams for D:\Unreal Projects\ue4-mediapipe-plugin\MediaPipeDemo.uproject
UATHelper: Packaging (Windows (64-bit)): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows (64-bit)): Running: C:\Program Files\Epic Games\UE_4.27\Engine\Binaries\DotNET\UnrealBuildTool.exe MediaPipeDemo Win64 Shipping -Project="D:\Unreal Projects\ue4-mediapipe-plugin\MediaPipeDemo.uproject" -Clean -NoHotReload "D:\Unreal Projects\ue4-mediapipe-plugin\MediaPipeDemo.uproject" -NoUBTMakefiles  -remoteini="D:\Unreal Proj
ects\ue4-mediapipe-plugin" -skipdeploy -distribution -nobuilduht -log="C:\Users\Dex-lab\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\UBT-MediaPipeDemo-Win64-Shipping.txt"
UATHelper: Packaging (Windows (64-bit)):   Cleaning MediaPipeDemo binaries...
UATHelper: Packaging (Windows (64-bit)): Took 1.1431025s to run UnrealBuildTool.exe, ExitCode=0
UATHelper: Packaging (Windows (64-bit)): Running: C:\Program Files\Epic Games\UE_4.27\Engine\Binaries\DotNET\UnrealBuildTool.exe MediaPipeDemo Win64 Shipping -Project="D:\Unreal Projects\ue4-mediapipe-plugin\MediaPipeDemo.uproject"  "D:\Unreal Projects\ue4-mediapipe-plugin\MediaPipeDemo.uproject" -NoUBTMakefiles  -remoteini="D:\Unreal Projects\ue4-mediapipe-
plugin" -skipdeploy -distribution -Manifest="D:\Unreal Projects\ue4-mediapipe-plugin\Intermediate\Build\Manifest.xml" -NoHotReload -log="C:\Users\Dex-lab\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\UBT-MediaPipeDemo-Win64-Shipping_2.txt"
UATHelper: Packaging (Windows (64-bit)):   Using 'git status' to determine working set for adaptive non-unity build (D:\Unreal Projects\ue4-mediapipe-plugin).
UATHelper: Packaging (Windows (64-bit)):   Parsing headers for MediaPipeDemo
UATHelper: Packaging (Windows (64-bit)):     Running UnrealHeaderTool "D:\Unreal Projects\ue4-mediapipe-plugin\MediaPipeDemo.uproject" "D:\Unreal Projects\ue4-mediapipe-plugin\Intermediate\Build\Win64\MediaPipeDemo\Shipping\MediaPipeDemo.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\User
s\Dex-lab\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\UHT-MediaPipeDemo-Win64-Shipping_2.txt" -installed
UATHelper: Packaging (Windows (64-bit)):   LogInit: Display: Loading text-based GConfig....
UATHelper: Packaging (Windows (64-bit)):   Reflection code generated for MediaPipeDemo in 4.7631709 seconds
UATHelper: Packaging (Windows (64-bit)):   Writing manifest to D:\Unreal Projects\ue4-mediapipe-plugin\Intermediate\Build\Manifest.xml
UATHelper: Packaging (Windows (64-bit)):   Building MediaPipeDemo...
UATHelper: Packaging (Windows (64-bit)):   Using Visual Studio 2019 14.29.30137 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: Packaging (Windows (64-bit)):   Building 42 actions with 8 processes...
UATHelper: Packaging (Windows (64-bit)):     [1/42] mesh_3d.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [2/42] classification.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [3/42] landmark.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [4/42] locus.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [5/42] environment.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [6/42] time_series_header.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [7/42] rect.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [8/42] MediaPipePresenceObserverComponent.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [9/42] MediaPipeObserverComponent.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [10/42] detection.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [11/42] image_file_properties.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [12/42] rasterization.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [13/42] MediaPipeClassificationObserverComponent.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [14/42] MediaPipeLandmarkObserverComponent.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [15/42] matrix_data.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [16/42] MediaPipePipelineComponent.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [17/42] anchor.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [18/42] image_format.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [19/42] MediaPipeClassificationObserverComponent.cpp
UATHelper: Packaging (Windows (64-bit)):     [20/42] MediaPipeFaceMeshObserverComponent.cpp
LogUdpMessaging: Warning: FUdpMessageProcessor::UpdateReassemblers Discarding 1/2 of stale message segements from Sender=10.235.10.219:63482, Sequence=0
UATHelper: Packaging (Windows (64-bit)):     [21/42] geometry_pipeline_metadata.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [22/42] location_data.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [23/42] MediaPipePipelineComponent.cpp
UATHelper: Packaging (Windows (64-bit)):     [24/42] MediaPipeFaceMeshObserverComponent.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [25/42] optical_flow_field_data.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [26/42] MediaPipePresenceObserverComponent.cpp
UATHelper: Packaging (Windows (64-bit)):     [27/42] Default.rc2
UATHelper: Packaging (Windows (64-bit)):     [28/42] MediaPipeLandmarkObserverComponent.cpp
UATHelper: Packaging (Windows (64-bit)):     [29/42] face_geometry.pb.cc
UATHelper: Packaging (Windows (64-bit)):     [30/42] MediaPipeModule.cpp
UATHelper: Packaging (Windows (64-bit)):     [31/42] MediaPipeObserverComponent.cpp
UATHelper: Packaging (Windows (64-bit)):     [32/42] MediaPipe.init.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [33/42] DynamicTexture.cpp
UATHelper: Packaging (Windows (64-bit)):     [34/42] SharedPCH.Engine.ShadowErrors.cpp
UATHelper: Packaging (Windows (64-bit)):     [35/42] Module.OVRLipSync.cpp
UATHelper: Packaging (Windows (64-bit)):     D:/Unreal Projects/ue4-mediapipe-plugin/Plugins/OVRLipSync/Source/OVRLipSync/Private/CookFrameSequenceAsync.cpp(7): fatal error C1083: Cannot open include file: 'Async.h': No such file or directory
UATHelper: Packaging (Windows (64-bit)):     [36/42] Module.OVRLipSync.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     D:\Unreal Projects\ue4-mediapipe-plugin\Plugins\OVRLipSync\Source\OVRLipSync/Public/OVRLipSyncPlaybackActorComponent.h(26): fatal error C1083: Cannot open include file: 'Classes/Components/AudioComponent.h': No such file or directory
UATHelper: Packaging (Windows (64-bit)):     [37/42] MediaPipeDemo.cpp
UATHelper: Packaging (Windows (64-bit)):     [38/42] MediaPipeDemo.init.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [39/42] MediaPipeCppExample.cpp
UATHelper: Packaging (Windows (64-bit)):     [40/42] MediaPipeCppExample.gen.cpp
UATHelper: Packaging (Windows (64-bit)): Took 65.7694112s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\Dex-lab\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\UBT-MediaPipeDemo-Win64-Shipping_2.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error`

**Comment by wongfei** [comment]
seems not mediapipe issue, but maybe related to precompiled header mode,

CookFrameSequenceAsync.cpp(7): fatal error C1083: Cannot open include file: 'Async.h'

OVRLipSyncPlaybackActorComponent.h(26): fatal error C1083: Cannot open include file: 'Classes/Components/AudioComponent.h'

possible fix:

#include "Async/Async.h"

#include "Components/AudioComponent.h"

**Comment by tbKorber** [comment]
MY GOODNESS, THANK YOU SO MUCH WONG FEI THIS WAS LITERALLY THE ANSWER! <3
