### ISSUE TITLE
BlackScreen after Package for windows. UE 5.01

### ISSUE THREAD

**Issue by UmkaApps** [wongfei/ue4-mediapipe-plugin#36]
Good afternoon. The last source. When packing a project under Windows, I can't start the resulting application. The application window freezes and nothing else happens. Even on an empty map. In the editor, everything starts and works like a charm.

**Comment by wongfei** [comment]
shipping should also work and maybe try https://github.com/wongfei/ue4-mediapipe-plugin/commit/c502349e4c0c8960cebbbd294397a157c38e00a1

**Comment by UmkaApps** [comment]
It works now. Thanks :)

**Comment by wongfei** [comment]
let's hope epic will fix that mess because i'm not doing these hacks for each upcoming version :D
