### ISSUE TITLE
Turning the 'enable overlay' variable to false breaks the hand landmarks.

### ISSUE THREAD

**Issue by EDsizm** [wongfei/ue4-mediapipe-plugin#38]
Hello! I am nearing my project's end using this awesome plugin, but I'm facing a slight issue wrapping things up.

I don't want the Mediapipe window showing the raw camera feed to pop up on the final packaged project.
Turning the 'enable overlay' variable to false seems to do that, but it greatly reduces the performance of the hand landmark tracking.

My intended outcome is simply to prevent the extra window showing the webcam feed from popping up.
Am I doing this the wrong way?

Thank you.

**Comment by wongfei** [comment]
disabling overlay shouldn't affect the performance, can you reproduce it on plugin examples?

**Comment by EDsizm** [comment]
Yes, even on the plugin examples, turning off 'enable overlay' severely decreases the performance.

How I tested this is by packaging the plugin examples and testing it on other computers as well. 
When the build was packaged without 'enable overlay' left on, hand tracking became very jagged and inaccurate.

**Comment by wongfei** [comment]
check log file for error/warning spam messages

also update to https://github.com/wongfei/ue4-mediapipe-plugin/commit/80ceef798105c5215c98b2da1e9e189f87102260

it adds console command "stat MediaPipe" that will show number of processed packets per second (for hand tracking should be around 30)

**Comment by EDsizm** [comment]
I did not exactly solve the issue, but I found a good workaround.
Turning on 'EnableVideoTexture' seems to have the same effect. I just remove the mesh when I don't want it on the level.

I still don't understand what caused the issue but thank you for your time.
