### ISSUE TITLE
Questions about code location

### ISSUE THREAD

**Issue by donguk071** [wongfei/ue4-mediapipe-plugin#39]
Questions
where can I check the code that connects the landmark of the media pipe to the skeleton bones of the unreal engine? I want to learn that process! thanks

**Comment by ucaswindlike** [comment]
same question，how to retarget the mediapipe skeleton to ue4 skeleton? Thanks!

**Comment by wongfei** [comment]
plugin doesn't solve that issue, but maybe UE5 IK Retargeting will be useful: https://docs.unrealengine.com/5.0/en-US/ik-rig-animation-retargeting-in-unreal-engine/

**Comment by donguk071** [comment]
thanks a lot!!
