### ISSUE TITLE
The project does not open in UE 5.0.2

### ISSUE THREAD

**Issue by hyunwoolee0099** [wongfei/ue4-mediapipe-plugin#42]
If I try to open a project in UE 5.0.2, it will stop at 75% Initializing.

When I checked the log, I checked that there was no response after opening the ump_shared.dll file for the last time, but I'm not sure if this dll is really the problem.

How can I fix this?

Thank you for reading it.

**Comment by wongfei** [comment]
that's a bug in UE5 that Epic don't want to fix.. 

see https://github.com/wongfei/ue4-mediapipe-plugin/commit/c502349e4c0c8960cebbbd294397a157c38e00a1

**Comment by hyunwoolee0099** [comment]
Thank you for your quick reply. 

I read the issue c502349. 

`	const char* Variants[] = {
		// 5.0.0
		"48 89 5C 24 08 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 D9 48 81 EC B0 00 00 00 48 8B 05 B5 C6 B5 00", // dev editor (unrealeditor-core.dll)
		"48 89 5C 24 08 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 D9 48 81 EC B0 00 00 00 48 8B 05 CC CC CC CC 48 33 C4 48 89 45 17 4D 63 68 3C 33 C0", // dev game
	};`

I understood that the problem will be solved if I modify the byte code of the parts annotated with "dev editor (unrealeditor-core.dll) and "dev game" in the above code according to the changed "FModuleTrace::OnDllLoaded". Am I right to understand?

**Comment by wongfei** [comment]
Just to be sure for 100% it's the same bug, launch the editor and when it stuck check the log file, it should end with:

"GetDllHandle: ump_shared.dll"

If that so, have to recompile the engine or byte patch two versions of FModuleTrace::OnDllLoaded: one for development editor build, another for development game build, shipping should work without any patches because no tracing there. Maybe there are other/easier solutions but who knows..

**Comment by UmkaApps** [comment]
yep. Stuck on ump_shared.dll.  Dat unreal :(

**Comment by macleod1982** [comment]
Can you please make a short tutorial on how to get the byte sig of FModuleTrace::OnDllLoaded ?

**Comment by wongfei** [comment]
> Can you please make a short tutorial on how to get the byte sig

sorry but that topic is far away from short tutorial

**Comment by tiantianaixuexi** [comment]
大佬，请问什么时候有5.0.2版本的 字节码补丁？

**Comment by wongfei** [comment]
in case somebody interested in fix, upvote: https://forums.unrealengine.com/t/fplatformprocess-getdllhandle-causes-deadlock-when-loading-opencv-world/571735

**Comment by lucasjinreal** [comment]
Anyplan to add support for UE5?

**Comment by VictorXuwj** [comment]
> in case somebody interested in fix, upvote: https://forums.unrealengine.com/t/fplatformprocess-getdllhandle-causes-deadlock-when-loading-opencv-world/571735

hi,is it possible to add hand landmark to the avator?
