### ISSUE TITLE
OnDllLoaded NOT FOUND

### ISSUE THREAD

**Issue by sixtolink** [wongfei/ue4-mediapipe-plugin#43]
Problem:Editor load stop at 75% Initializing...

Windows OS: Win11 Enterprise 22000.739

UE Version: UE5 5.0.2

VS Version:VS2022 MSVC v143 - VS 2022 C++ x64/x86 toolchain(Laster)

Log:
Display      LogMediaPipe              FMediaPipeModule::StartupModule
Display      LogMediaPipe              FindPattern Id=0 Status=0 Count=0 [(null)]
Display      LogMediaPipe              FindPattern Id=1 Status=0 Count=0 [(null)]
Warning      LogMediaPipe              FModuleTrace::OnDllLoaded NOT FOUND
Display      LogMediaPipe              PluginBaseDir: D:/WorkSpace/UEProject/mediapipe_/Plugins/MediaPipe
Display      LogMediaPipe              BinariesDir: D:/WorkSpace/UEProject/mediapipe_/Plugins/MediaPipe/Binaries/Win64
Display      LogMediaPipe              DataDir: D:/WorkSpace/UEProject/mediapipe_/Plugins/MediaPipe/ThirdParty/mediapipe/Data
Display      LogMediaPipe              GetDllHandle: D:/WorkSpace/UEProject/mediapipe_/Plugins/MediaPipe/Binaries/Win64/ump_shared.dll

**Comment by wongfei** [comment]
https://github.com/wongfei/ue4-mediapipe-plugin/issues/42
