### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by wwdok** [wongfei/ue4-mediapipe-plugin#44]
Hello, @wongfei , i am totally new to UE, ( i am familiar with mediapipe), recently i am getting started with learning UE, then i want to start with playing mediapipe in UE, then i find your this plugin, but i don't know how to install and use it in UE, could you please add more tutorial in README.md ? or tell me some related tutorial link ~

**Comment by wwdok** [comment]
I try to use UE 4.27.2 to open MediaPipeDemo.uproject in the root folder, but it pop out following warning :
![image](https://user-images.githubusercontent.com/43233772/174700613-5745e474-dead-4615-9e7e-6aaec416aeb3.png)
I click Yes, then it pop out error:
![image](https://user-images.githubusercontent.com/43233772/174700662-37605fe5-198a-4a41-9cdf-170d5c97492f.png)

**Comment by CoderJackLiu** [comment]
Try to rebuild it in vs or other ide like rider. It may be help.

**Comment by LightQniX** [comment]
can I detect multiple faces in the camera? If so, please tell me how?
