### ISSUE TITLE
Multiple faces

### ISSUE THREAD

**Issue by LightQniX** [wongfei/ue4-mediapipe-plugin#46]
Can I detect multiple faces in the camera? If so, please tell me how?

**Comment by wongfei** [comment]
not supported

**Comment by LightQniX** [comment]
Thanks!

**Comment by LightQniX** [comment]
![image](https://user-images.githubusercontent.com/37746676/179697761-606aa90d-9040-4b66-823a-046ba4d05e99.png)

Supports
