### ISSUE TITLE
[QUESTION] Can you give some info of how to implement another models?

### ISSUE THREAD

**Issue by iMaciaP** [wongfei/ue4-mediapipe-plugin#5]
Thank you for the plugin, very nice job!.

As i ask, can you give some details or docs of how to implement another model like "objectron" from mediapipe into the plugin with c++? Best regards.

**Comment by wongfei** [comment]
For some unknown reason objectron examples don't work on my desktop, consider it unsupported right now..

But theoretically plugin is able to run objectron pipeline.

Check:

https://github.com/wongfei/ue4-mediapipe-plugin/blob/master/Plugins/MediaPipe/ThirdParty/mediapipe/Data/mediapipe/unreal/objectron_landmarks.pbtxt
