### ISSUE TITLE
 LogMediaPipe: Error: ObjectId out of range

### ISSUE THREAD

**Issue by salier** [wongfei/ue4-mediapipe-plugin#8]
[log.txt](https://github.com/wongfei/ue4-mediapipe-plugin/files/7082290/log.txt)
An error is reported at runtime logmediapipe: error: objectid out of range
The number of frames is greatly reduced (from 200 frames to about 60 frames)
The array length of 0 is the camera start-up time (or the face is not recognized)

**Comment by wongfei** [comment]
OptionA: use new API TryGet*

OptionB: always ensure ID's in range before accessing data with Get functions

OptionC: comment/disable "out of range" traces in Get functions

![mp_tryget](https://user-images.githubusercontent.com/13559668/131482711-a41fcee8-31ba-4d45-915c-92670174429c.jpg)

![mp_get](https://user-images.githubusercontent.com/13559668/131482694-98525ba6-8cd8-402c-9fb8-282b6e65fba4.jpg)

https://github.com/wongfei/ue4-mediapipe-plugin/blob/master/Plugins/MediaPipe/Source/MediaPipe/Private/MediaPipeLandmarkObserverComponent.cpp#L114

**Comment by salier** [comment]
![image](https://user-images.githubusercontent.com/28691601/131772425-bad4ca35-ba6d-4964-b7d7-0f8f86b507c6.png)
I use a new version of plug-in. And a new API. But it doesn't work properly. The recognition is normal, but there is no output data
![image](https://user-images.githubusercontent.com/28691601/131772537-918fd11f-4dd0-4947-8edc-2c43ee7eb81d.png)

**Comment by salier** [comment]
Even the original node is still unavailable

**Comment by salier** [comment]
![image](https://user-images.githubusercontent.com/28691601/131775885-9fc63e36-ac44-4035-9e6d-12b50bb515e5.png)

UATHelper: 打包 (Windows (64-bit)):   Parsing headers for MediaPipeDemo
UATHelper: 打包 (Windows (64-bit)):     Running UnrealHeaderTool "E:\unral project\apipe\MediaPipeDemo.uproject" "E:\unral project\apipe\Intermediate\Build\Win64\MediaPipeDemo\Development\MediaPipeDemo.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\Administrator\AppData\Roaming\Unreal
 Engine\AutomationTool\Logs\D+UE_4.26\UHT-MediaPipeDemo-Win64-Development.txt" -installed
UATHelper: 打包 (Windows (64-bit)):   Reflection code generated for MediaPipeDemo in 4.0280043 seconds
UATHelper: 打包 (Windows (64-bit)):   Writing manifest to E:\unral project\apipe\Intermediate\Build\Manifest.xml
UATHelper: 打包 (Windows (64-bit)):   Failed to delete file 'E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll'
UATHelper: 打包 (Windows (64-bit)):       Exception: 对路径“E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll”的访问被拒绝。
UATHelper: 打包 (Windows (64-bit)):   Attempting to retry...
UATHelper: 打包 (Windows (64-bit)):   Failed to delete file 'E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll'
UATHelper: 打包 (Windows (64-bit)):       Exception: 对路径“E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll”的访问被拒绝。
UATHelper: 打包 (Windows (64-bit)):   Attempting to retry...
UATHelper: 打包 (Windows (64-bit)):   Failed to delete file 'E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll'
UATHelper: 打包 (Windows (64-bit)):       Exception: 对路径“E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll”的访问被拒绝。
UATHelper: 打包 (Windows (64-bit)):   ERROR: Exhausted all retries!
UATHelper: 打包 (Windows (64-bit)):   Building MediaPipeDemo...
UATHelper: 打包 (Windows (64-bit)):   Using Visual Studio 2019 14.29.30037 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037) and Windows 10.0.20348.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]
UATHelper: 打包 (Windows (64-bit)):   [Upgrade] Using backward-compatible build settings. The latest version of UE4 sets the following values by default, which may require code changes:
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]     bLegacyPublicIncludePaths = false                 => Omits subfolders from public include paths to reduce compiler command line length. (Previously: true).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]     ShadowVariableWarningLevel = WarningLevel.Error   => Treats shadowed variable warnings as errors. (Previously: WarningLevel.Warning).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]     PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs   => Set in build.cs files to enables IWYU-style PCH model. See https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/IWYU/index.html. (Previously: PCHUsageMode.UseSharedPCHs).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade] Suppress this message by setting 'DefaultBuildSettings = BuildSettingsVersion.V2;' in MediaPipeDemo.Target.cs, and explicitly overriding settings that differ from the new defaults.
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]
UATHelper: 打包 (Windows (64-bit)):   Building 45 actions with 8 processes...
PackagingResults: Error: Exhausted all retries!
I solved the problem of previous data. But I found it on the way of packaging. Although the packaging is still displayed and running, the output log is stuck here

**Comment by salier** [comment]
After a crash, it is packed again
UATHelper: 打包 (Windows (64-bit)):   Writing manifest to E:\unral project\apipe\Intermediate\Build\Manifest.xml
UATHelper: 打包 (Windows (64-bit)):   Failed to delete file 'E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll'
UATHelper: 打包 (Windows (64-bit)):       Exception: 对路径“E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll”的访问被拒绝。
UATHelper: 打包 (Windows (64-bit)):   Attempting to retry...
UATHelper: 打包 (Windows (64-bit)):   Failed to delete file 'E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll'
UATHelper: 打包 (Windows (64-bit)):       Exception: 对路径“E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll”的访问被拒绝。
UATHelper: 打包 (Windows (64-bit)):   Attempting to retry...
UATHelper: 打包 (Windows (64-bit)):   Failed to delete file 'E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll'
UATHelper: 打包 (Windows (64-bit)):       Exception: 对路径“E:\unral project\apipe\Binaries\Win64\opencv_world3410.dll”的访问被拒绝。
UATHelper: 打包 (Windows (64-bit)):   ERROR: Exhausted all retries!
UATHelper: 打包 (Windows (64-bit)):   Building MediaPipeDemo...
UATHelper: 打包 (Windows (64-bit)):   Using Visual Studio 2019 14.29.30037 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037) and Windows 10.0.20348.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]
UATHelper: 打包 (Windows (64-bit)):   [Upgrade] Using backward-compatible build settings. The latest version of UE4 sets the following values by default, which may require code changes:
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]     bLegacyPublicIncludePaths = false                 => Omits subfolders from public include paths to reduce compiler command line length. (Previously: true).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]     ShadowVariableWarningLevel = WarningLevel.Error   => Treats shadowed variable warnings as errors. (Previously: WarningLevel.Warning).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]     PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs   => Set in build.cs files to enables IWYU-style PCH model. See https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/IWYU/index.html. (Previously: PCHUsageMode.UseSharedPCHs).
UATHelper: 打包 (Windows (64-bit)):   [Upgrade] Suppress this message by setting 'DefaultBuildSettings = BuildSettingsVersion.V2;' in MediaPipeDemo.Target.cs, and explicitly overriding settings that differ from the new defaults.
UATHelper: 打包 (Windows (64-bit)):   [Upgrade]
UATHelper: 打包 (Windows (64-bit)):   Building 2 actions with 8 processes...
UATHelper: 打包 (Windows (64-bit)):     [1/2] opencv_world3410.dll
UATHelper: 打包 (Windows (64-bit)):     ��һ����������ʹ�ô��ļ��������޷����ʡ�
UATHelper: 打包 (Windows (64-bit)): Took 4.5649995s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: 打包 (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE_4.26\UBT-MediaPipeDemo-Win64-Development.txt)
UATHelper: 打包 (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
PackagingResults: Error: Exhausted all retries!
LogSlate: Last resort fallback font was requested. Font: '../../../Engine/Content/Slate/Fonts/DroidSansFallback.ttf', Character: 'ʹ (U+02b9)'
UATHelper: 打包 (Windows (64-bit)): BUILD FAILED
LogSlate: Took 0.040102 seconds to synchronously load lazily loaded font '../../../Engine/Content/SlateDebug/Fonts/LastResort.ttf' (5269K)
PackagingResults: Error: Unknown Error
[UBT-MediaPipeDemo-Win64-Development.txt](https://github.com/wongfei/ue4-mediapipe-plugin/files/7095738/UBT-MediaPipeDemo-Win64-Development.txt)

**Comment by salier** [comment]
[log.txt](https://github.com/wongfei/ue4-mediapipe-plugin/files/7095885/log.txt)
This is an old plug-in. Packaged log

**Comment by wongfei** [comment]
close the project, ensure in task manager that ue4editor.exe is not running, then delete directories in project folder:

Binaries
Build
Intermediate
Saved 
Plugins\MediaPipe\Binaries
Plugins\MediaPipe\Intermediate
